/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    addons: Addon;
    faqs: Faq;
    testimonials: Testimonial;
    categories: Category;
    resources: Resource;
    products: Product;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    addons: AddonsSelect<false> | AddonsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    homepage: Homepage;
    'shop-settings': ShopSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'shop-settings': ShopSettingsSelect<false> | ShopSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons".
 */
export interface Addon {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  q: string;
  a: string;
  categories?: (number | Category)[] | null;
  products?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  slug: string;
  title: string;
  label: string;
  eyebrow?: string | null;
  summary?: string | null;
  description?: string | null;
  parent?: (number | null) | Category;
  heroImage: number | Media;
  gallery?:
    | {
        image: number | Media;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  pricing?:
    | {
        name: string;
        price: string;
        featured?: boolean | null;
        includes?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  addons?: (number | Addon)[] | null;
  related?: (number | Category)[] | null;
  testimonials?: (number | Testimonial)[] | null;
  videos?:
    | {
        title: string;
        embed?: string | null;
        id?: string | null;
      }[]
    | null;
  bts?:
    | {
        title: string;
        copy: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  rating: number;
  quote: string;
  category?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  slug: string;
  name: string;
  startingPrice: number;
  priceLabel: string;
  summary: string;
  shortDescription: string;
  heroImage: number | Media;
  gallery?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  rating?: string | null;
  reviewCount?: number | null;
  variants?:
    | {
        name: string;
        key: string;
        options?:
          | {
              label: string;
              price: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  personalizationFields?:
    | {
        label: string;
        key: string;
        placeholder?: string | null;
        id?: string | null;
      }[]
    | null;
  upload: {
    min: number;
    max: number;
    multiple?: boolean | null;
    guidance: string;
  };
  details?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  howItWorks?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  reviews?:
    | {
        name: string;
        quote: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  slug: string;
  title: string;
  category?: (number | null) | Category;
  excerpt: string;
  image: number | Media;
  contentPoints?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'addons';
        value: number | Addon;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons_select".
 */
export interface AddonsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  q?: T;
  a?: T;
  categories?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  rating?: T;
  quote?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  label?: T;
  eyebrow?: T;
  summary?: T;
  description?: T;
  parent?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        name?: T;
        price?: T;
        featured?: T;
        includes?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  addons?: T;
  related?: T;
  testimonials?: T;
  videos?:
    | T
    | {
        title?: T;
        embed?: T;
        id?: T;
      };
  bts?:
    | T
    | {
        title?: T;
        copy?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  excerpt?: T;
  image?: T;
  contentPoints?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  startingPrice?: T;
  priceLabel?: T;
  summary?: T;
  shortDescription?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  rating?: T;
  reviewCount?: T;
  variants?:
    | T
    | {
        name?: T;
        key?: T;
        options?:
          | T
          | {
              label?: T;
              price?: T;
              id?: T;
            };
        id?: T;
      };
  personalizationFields?:
    | T
    | {
        label?: T;
        key?: T;
        placeholder?: T;
        id?: T;
      };
  upload?:
    | T
    | {
        min?: T;
        max?: T;
        multiple?: T;
        guidance?: T;
      };
  details?:
    | T
    | {
        item?: T;
        id?: T;
      };
  howItWorks?:
    | T
    | {
        item?: T;
        id?: T;
      };
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  reviews?:
    | T
    | {
        name?: T;
        quote?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  domain: string;
  tagline?: string | null;
  description?: string | null;
  phone: string;
  phoneHref: string;
  whatsapp: string;
  email: string;
  address: string;
  googleMapsUrl?: string | null;
  rating?: string | null;
  reviewCount?: string | null;
  analyticsId?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  heroCtaLabels?: {
    primary?: string | null;
    secondary?: string | null;
  };
  footerText?: {
    copyright?: string | null;
    description?: string | null;
  };
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  logo: number | Media;
  favicon?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  primaryNavigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerNavigation?: {
    studioLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  ctaButtons?: {
    headerBookNow?: {
      label?: string | null;
      href?: string | null;
    };
    footerWhatsApp?: {
      label?: string | null;
      href?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  hero: {
    eyebrow: string;
    title: string;
    copy: string;
    image: number | Media;
    primaryCta?: string | null;
    secondaryCta?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    trust?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  story: {
    eyebrow: string;
    title: string;
    copy: string;
    image: number | Media;
    points?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  resources?: (number | Resource)[] | null;
  categories?: (number | Category)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings".
 */
export interface ShopSetting {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  hero: {
    eyebrow: string;
    title: string;
    copy: string;
    image: number | Media;
  };
  why?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  tagline?: T;
  description?: T;
  phone?: T;
  phoneHref?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  googleMapsUrl?: T;
  rating?: T;
  reviewCount?: T;
  analyticsId?: T;
  instagram?: T;
  youtube?: T;
  heroCtaLabels?:
    | T
    | {
        primary?: T;
        secondary?: T;
      };
  footerText?:
    | T
    | {
        copyright?: T;
        description?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  logo?: T;
  favicon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primaryNavigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerNavigation?:
    | T
    | {
        studioLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  ctaButtons?:
    | T
    | {
        headerBookNow?:
          | T
          | {
              label?: T;
              href?: T;
            };
        footerWhatsApp?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        copy?: T;
        image?: T;
        primaryCta?: T;
        secondaryCta?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        trust?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  story?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        copy?: T;
        image?: T;
        points?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  resources?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings_select".
 */
export interface ShopSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        copy?: T;
        image?: T;
      };
  why?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}